#!/bin/bash
set -euo pipefail
work=/home/$USER/work/ppg_bp; archive=/home/$USER/nas/ppg_bp; root=$work/code/pulsedb_fewshot; cd $root; seed=20260821
declare -a jobs specs
methods=(ridge mlp gated_mlp weighted_mlp causal_gru supervised_moe); labels=("R7-1 Ridge residual" "R7-2 Residual MLP" "R7-3 Confidence-gated residual" "R7-4 Difficult-2x residual" "R7-5 Causal feature GRU" "R7-6 Supervised MoE")
for i in ${!methods[@]}; do if [[ ${methods[$i]} == ridge ]]; then job=$(sbatch --parsable --job-name=ppg_r7_${methods[$i]} scripts/sbatch_phase6e_train.sh ${methods[$i]} $seed); elif ((i%2)); then job=$(sbatch --parsable --gres=gpu:rtx_5080:1 --job-name=ppg_r7_${methods[$i]} scripts/sbatch_phase6e_train.sh ${methods[$i]} $seed); else job=$(sbatch --parsable --gres=gpu:rtx_5070_ti:1 --job-name=ppg_r7_${methods[$i]} scripts/sbatch_phase6e_train.sh ${methods[$i]} $seed); fi; jobs+=($job); specs+=("${labels[$i]}=$work/outputs/event120-v1_phase6e_${methods[$i]}_seed${seed}_job${job}"); done
router=$(sbatch --parsable scripts/sbatch_round7_router.sh $seed); router_dir=$work/outputs/event120-v1_round7_phenotype_router_seed${seed}_job${router}
hard=$(sbatch --parsable --dependency=afterok:$router --gres=gpu:rtx_5070_ti:1 --job-name=ppg_r7_pheno_hard scripts/sbatch_round7_deep.sh phenotype_hard $router_dir $seed); jobs+=($hard); specs+=("R7-7 Two-stage phenotype hard route=$work/outputs/event120-v1_round7_phenotype_hard_seed${seed}_job${hard}")
soft=$(sbatch --parsable --dependency=afterok:$router --gres=gpu:rtx_5080:1 --job-name=ppg_r7_pheno_soft scripts/sbatch_round7_deep.sh phenotype_soft $router_dir $seed); jobs+=($soft); specs+=("R7-8 Two-stage phenotype soft route=$work/outputs/event120-v1_round7_phenotype_soft_seed${seed}_job${soft}")
deep=$(sbatch --parsable --dependency=afterok:$router --gres=gpu:rtx_5080:1 --job-name=ppg_r7_embedding_gru scripts/sbatch_round7_deep.sh embedding_gru $router_dir $seed); jobs+=($deep); specs+=("R7-9 Waveform-embedding causal GRU=$work/outputs/event120-v1_round7_embedding_gru_seed${seed}_job${deep}")
dependency=$(IFS=:; echo "${jobs[*]}"); report=$(sbatch --parsable --dependency=afterok:$dependency scripts/sbatch_phase6e_report.sh "${specs[@]}")
manifest=$work/outputs/submission_manifests/event120-v1_round7_nine_routes_$(date +%Y%m%d-%H%M%S).txt; { echo ROUND=7; echo LOCKED_META_TEST_ACCESSED=no; echo ROUTER_JOB=$router; for i in ${!jobs[@]}; do echo CANDIDATE_$i=${jobs[$i]}; done; echo REPORT_JOB=$report; echo PROMOTION_GATE=overall_gain_at_least_0.15_mmHg_and_both_sources_improve; } | tee $manifest; mkdir -p $archive/outputs/submission_manifests; cp $manifest $archive/outputs/submission_manifests/
